Update Keepalived unicast config validation
openshift/baremetal-runtimecfg pull request #116
Opened 2021-01-20 11:07 UTC by yboaron

In the case of unicast, Keepalived configuration on masters/workers can only
be updated if the node appears in the backends list.

2021-01-20 11:41 UTC, yboaron commented
/retitle Bug 1913705: Update Keepalived unicast config validation

2021-01-20 15:11 UTC, yboaron commented
/test e2e-metal-ipi

2021-01-21 17:12 UTC, cybertron requested changes
Can we just modify the keepalived signal handler to ignore reload if keepalived was previously stopped? IIUC, that would also fix the problem here and it would be a lot simpler than adding more thresholds.

2021-01-28 08:07 UTC, yboaron commented on pkg/monitor/dynkeepalived.go
> +	log.Info("Test version Test Version Latest ! !!!!!!!!!")
Marius uses the ci BOT to create a release with this PR for testing , we wanted to make sure he was using the correct baremetal-runtimecfg image ...

I'll delete this line

2021-01-28 08:29 UTC, yboaron commented
> Can we just modify the keepalived signal handler to ignore reload if keepalived was previously stopped? IIUC, that would also fix the problem here and it would be a lot simpler than adding more thresholds.

Well, I added this change for two reasons:
A.  Make sure that sending multiple reload messages doesn't cause Keepalived or Keepalived-monitor  hang on for ~ 20 minutes. 
B.  Check if adding threshold also for start helps.

It seems that this change didn't solve the hang on issue , so I think I'll delete this change from PR.

2021-02-03 10:14 UTC, yboaron commented
/retitle Update Keepalived unicast config validation

2021-03-04 13:39 UTC, closed without merging